{
 "title": "Game Stats",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Logins by Player",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(loggedin_player_total) by (player_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "New Players",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(register_player_total)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Partidas jugadas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum(total_games) by (player_name))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Daño inflingido por jugadores",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "topk(10, sum(total_damage) by (player_name))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}